/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import javax.swing.JOptionPane;
import modelo.Categoria;
import dao.CategoriaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chemo
 */
public class VtnCategorias extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnCategorias
     */
    public VtnCategorias()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        buscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarCategorias();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarCategorias();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarCategorias();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategoria = new javax.swing.JTable();
        categoriaJT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripccionJT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        activoCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID CATEGORIA", "NOMBRE", "DESCRIPCCION", "ACTIVO", "FECHA CREACION"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaCategoria.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCategoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 770, -1));
        jPanel1.add(categoriaJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 370, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        descripccionJT.setColumns(20);
        descripccionJT.setRows(5);
        jScrollPane2.setViewportView(descripccionJT);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 370, -1));

        jLabel3.setText("Descripccion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        jLabel1.setText("Categorias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 100, 20));

        activoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(activoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, -1, -1));

        jLabel4.setText("Activo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, -1, -1));
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 650, -1));

        jLabel5.setText("Baja");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String nombre = categoriaJT.getText().trim();
        String descripcion = descripccionJT.getText().trim();
        String estado = (String) activoCB.getSelectedItem();

        if (nombre.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (descripcion.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean activo = estado.equalsIgnoreCase("Activo");

        Categoria nuevaCategoria = new Categoria(nombre, descripcion, activo);

        boolean exito = CategoriaDAO.agregarCategoria(nuevaCategoria);

        if (exito)
        {
            JOptionPane.showMessageDialog(this, "Categoría registrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(categoriaJT, descripcion);
            activoCB.setSelectedIndex(0);
            llenarTablaCategorias();
        } else
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaCategorias();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tablaCategoriaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaCategoriaMouseClicked
    {//GEN-HEADEREND:event_tablaCategoriaMouseClicked
        int filaSeleccionada = tablaCategoria.getSelectedRow();

        if (filaSeleccionada != -1)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaCategoria.getModel();
            String nombreCategoria = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
            String descripcion = (String) modeloTabla.getValueAt(filaSeleccionada, 2);
            String estado = (String) modeloTabla.getValueAt(filaSeleccionada, 3);

            categoriaJT.setText(nombreCategoria);
            descripccionJT.setText(descripcion);

            if (estado.equals("Activo"))
            {
                activoCB.setSelectedItem("Activo");
            } else
            {
                activoCB.setSelectedItem("Inactivo");
            }
        }
    }//GEN-LAST:event_tablaCategoriaMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel5MouseClicked
    {//GEN-HEADEREND:event_jLabel5MouseClicked
        int filaSeleccionada = tablaCategoria.getSelectedRow();

        if (filaSeleccionada < 0 || filaSeleccionada >= tablaCategoria.getRowCount())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar la categoría seleccionada?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaCategoria.getModel();
            Object valorCelda = tablaCategoria.getValueAt(filaSeleccionada, 0);

            long categoriaId;
            try
            {
                categoriaId = Long.parseLong(valorCelda.toString());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error al obtener el código de la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            CategoriaDAO categoriaDAO = new CategoriaDAO();
            categoriaDAO.eliminarCategoria(categoriaId);

            llenarTablaCategorias();
            JOptionPane.showMessageDialog(this, "Categoría eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(categoriaJT, descripccionJT);
            activoCB.setSelectedIndex(0);

        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        CtrlInterfaz.limpia(categoriaJT, descripccionJT);
        activoCB.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        int filaSeleccionada = tablaCategoria.getSelectedRow();

        if (filaSeleccionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCategoria.getModel();

        String nuevoNombre = categoriaJT.getText();
        String nuevaDescripcion = descripccionJT.getText();
        String estadoSeleccionado = activoCB.getSelectedItem().toString();

        boolean activo = estadoSeleccionado.equalsIgnoreCase("Activo");

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        Categoria categoriaActualizada = new Categoria();

        Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);
        int categoriaId;

        try
        {
            categoriaId = Integer.parseInt(valorCelda.toString());
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID de la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        categoriaActualizada.setId_categoria(categoriaId);
        categoriaActualizada.setNombre(nuevoNombre);
        categoriaActualizada.setDescripccion(nuevaDescripcion);
        categoriaActualizada.setActivo(activo);

        boolean exito = categoriaDAO.modificarCategoria(categoriaActualizada);

        if (exito)
        {
            JOptionPane.showMessageDialog(this, "Categoría actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            llenarTablaCategorias();
        } else
        {
            JOptionPane.showMessageDialog(this, "Error al actualizar la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void llenarTablaCategorias()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaCategoria.getModel();

        modelo.setRowCount(0);

        List<modelo.Categoria> categorias = CategoriaDAO.listarCategorias();

        for (modelo.Categoria categoria : categorias)
        {
            modelo.addRow(new Object[]
            {
                categoria.getId_categoria(),
                categoria.getNombre(),
                categoria.getDescripccion(),
                categoria.isActivo() ? "Activo" : "Inactivo",
                categoria.getFecha_creacion()
            });
        }
    }

    public void filtrarCategorias()
    {
        String textoBusqueda = buscar.getText().trim().toLowerCase();
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCategoria.getModel();

        modeloTabla.setRowCount(0);

        CategoriaDAO categoriaDAO = new CategoriaDAO();

        List<Categoria> categorias = categoriaDAO.obtenerTodosLasCategorias();

        for (Categoria categoria : categorias)
        {
            if (categoria.getNombre().toLowerCase().contains(textoBusqueda))
            {
                Object[] fila =
                {
                    categoria.getId_categoria(),
                    categoria.getNombre(),
                    categoria.getDescripccion(),
                    categoria.isActivo() ? "Activo" : "Inactivo",
                    categoria.getFecha_creacion()
                };
                modeloTabla.addRow(fila);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activoCB;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField categoriaJT;
    private javax.swing.JTextArea descripccionJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCategoria;
    // End of variables declaration//GEN-END:variables
}
