/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.ClienteDAO;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author chemo
 */
public class VtnClientes extends javax.swing.JInternalFrame
{

    private com.toedter.calendar.JDateChooser fecha;

    /**
     * Creates new form VtnEmpleados
     */
    public VtnClientes()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        fecha = new com.toedter.calendar.JDateChooser();

        fecha.setBounds(0, 0, 150, 30);

        calendario.setLayout(null);

        calendario.add(fecha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        direccionJT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreJT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoJT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoJT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailJT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordJT = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        activoCB = new javax.swing.JComboBox<>();
        calendario = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        contraCB = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "NOMBRE", "APELLIDO", "TELEFONO", "E-MAIL", "DIRECCION", "FECHA NACIMIENTO", "PASSWORD", "FECHA REGISTRO", "ACTIVO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 400));

        jLabel1.setText("activo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        direccionJT.setToolTipText("");
        jPanel1.add(direccionJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 350, -1));

        jLabel2.setText("nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));
        jPanel1.add(nombreJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 350, -1));

        jLabel3.setText("apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));
        jPanel1.add(apellidoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 350, -1));

        jLabel4.setText("telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));
        jPanel1.add(telefonoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 350, -1));

        jLabel5.setText("email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));
        jPanel1.add(emailJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 350, -1));

        jLabel6.setText("direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        jLabel7.setText("direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));
        jPanel1.add(passwordJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 350, -1));

        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        activoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO ", "INACTIVO" }));
        jPanel1.add(activoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, -1, -1));

        calendario.setBackground(new java.awt.Color(255, 255, 255));
        calendario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 150, 30));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 640, -1));

        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        jButton2.setText("modificar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, -1, -1));

        jButton3.setText("limpiar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 490, -1, -1));

        jLabel9.setText("clientes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        contraCB.setText("Mostrar Contraseña");
        contraCB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                contraCBActionPerformed(evt);
            }
        });
        jPanel1.add(contraCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, -1, -1));

        jLabel10.setText("Baja");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String nombre = nombreJT.getText().trim();
        String apellido = apellidoJT.getText().trim();
        String telefono = telefonoJT.getText().trim();
        String email = emailJT.getText().trim();
        String direccion = direccionJT.getText().trim();
        String password = passwordJT.getText().trim();
        boolean activo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");

        if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || email.isEmpty() || direccion.isEmpty() || password.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!telefono.matches("\\d{10}"))
        {
            JOptionPane.showMessageDialog(this, "Número de teléfono inválido. Debe contener exactamente 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$"))
        {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fecha.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date fechaSeleccionada = new java.sql.Date(fecha.getDate().getTime());

        Cliente nuevoCliente = new Cliente(nombre, apellido, telefono, email, direccion, fechaSeleccionada, password, activo);
        boolean registroExitoso = ClienteDAO.agregarCliente(nuevoCliente);

        if (registroExitoso)
        {
            JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(nombreJT, apellidoJT, telefonoJT, emailJT, direccionJT, passwordJT);
            fecha.setDate(null);
            llenarTablaClientes();
        } else
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contraCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_contraCBActionPerformed
    {//GEN-HEADEREND:event_contraCBActionPerformed
        if (contraCB.isSelected())
        {
            passwordJT.setEchoChar((char) 0);
        } else
        {
            passwordJT.setEchoChar('*');
        }
    }//GEN-LAST:event_contraCBActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaClientes();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel10MouseClicked
    {//GEN-HEADEREND:event_jLabel10MouseClicked
        int filaSeleccionada = tablaClientes.getSelectedRow();

        if (filaSeleccionada < 0 || filaSeleccionada >= tablaClientes.getRowCount())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar el cliente seleccionado?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaClientes.getModel();
            Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);

            int clienteID;
            try
            {
                clienteID = Integer.parseInt(valorCelda.toString());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error al obtener el ID del cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ClienteDAO clienteDAO = new ClienteDAO();
            boolean exito = clienteDAO.eliminarCliente(clienteID);

            if (exito)
            {
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTablaClientes();
                CtrlInterfaz.limpia(nombreJT, apellidoJT, telefonoJT, emailJT, direccionJT);
                fecha.setDate(null);
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaClientesMouseClicked
    {//GEN-HEADEREND:event_tablaClientesMouseClicked
        int filaSeleccionada = tablaClientes.getSelectedRow();

        if (filaSeleccionada != -1)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaClientes.getModel();

            String nombre = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
            String apellido = (String) modeloTabla.getValueAt(filaSeleccionada, 2);
            String telefono = (String) modeloTabla.getValueAt(filaSeleccionada, 3);
            String email = (String) modeloTabla.getValueAt(filaSeleccionada, 4);
            String direccion = (String) modeloTabla.getValueAt(filaSeleccionada, 5);
            Date fecha = (Date) modeloTabla.getValueAt(filaSeleccionada, 6);
            String password = (String) modeloTabla.getValueAt(filaSeleccionada, 7);
            Object estadoObj = modeloTabla.getValueAt(filaSeleccionada, 9); // Columna "activo" // Suponiendo que la columna 9 es "activo"

            nombreJT.setText(nombre);
            apellidoJT.setText(apellido);
            telefonoJT.setText(telefono);
            emailJT.setText(email);
            direccionJT.setText(direccion);
            this.fecha.setDate(fecha);
            passwordJT.setText(password);

            boolean activo = false;

            if (estadoObj instanceof Boolean)
            {
                activo = (Boolean) estadoObj;
            } else if (estadoObj instanceof Number)
            {
                activo = ((Number) estadoObj).intValue() == 1;
            } else
            {
                activo = estadoObj.toString().equals("1") || estadoObj.toString().equalsIgnoreCase("activo");
            }

            if (activo)
            {
                activoCB.setSelectedItem("ACTIVO");
            } else
            {
                activoCB.setSelectedItem("INACTIVO");
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void llenarTablaClientes()
    {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaClientes.getModel();
        modeloTabla.setRowCount(0);

        List<Cliente> listaClientes = ClienteDAO.obtenerClientes();

        for (Cliente c : listaClientes)
        {
            Object[] fila =
            {
                c.getCliente_id(),
                c.getNombre(),
                c.getApellido(),
                c.getTelefono(),
                c.getEmail(),
                c.getDireccion(),
                c.getFecha_nacimiento(),
                c.getPassword(),
                c.getFecha_registro(),
                c.isActivo() ? "Activo" : "Inactivo"
            };
            modeloTabla.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activoCB;
    private javax.swing.JTextField apellidoJT;
    private javax.swing.JPanel calendario;
    private javax.swing.JCheckBox contraCB;
    private javax.swing.JTextField direccionJT;
    private javax.swing.JTextField emailJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nombreJT;
    private javax.swing.JPasswordField passwordJT;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField telefonoJT;
    // End of variables declaration//GEN-END:variables
}
