/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import dao.DetalleVentaDAO;
import dao.VentaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author chemo
 */
public class VtnDetalleVenta extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnDetalleVenta
     */
    public VtnDetalleVenta()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        aaa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalleVenta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aaa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID VENTA", "FECHA", "CLIENTE", "EMPLEADO", "TOTAL", "DESCUENTO", "IMPUESTO", "METODO PAGO", "ESTADO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaVenta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVenta);

        aaa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 190));

        jLabel1.setText("TABLA VENTAS");
        aaa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        tablaDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID DETALLE", "ID VENTA", "PRODUCTO", "CANTIDAD", "PRECIO UNITARIO", "SUBTOTAL"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDetalleVenta);

        aaa.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1200, 280));

        jLabel2.setText("DETALLE VENTA");
        aaa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        getContentPane().add(aaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaVentas();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tablaVentaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaVentaMouseClicked
    {//GEN-HEADEREND:event_tablaVentaMouseClicked
        int fila = tablaVenta.getSelectedRow();
        if (fila != -1)
        {
            int ventaId = (int) tablaVenta.getValueAt(fila, 0);
            cargarDetallesPorVenta(ventaId);
        }
    }//GEN-LAST:event_tablaVentaMouseClicked

    public void llenarTablaVentas()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        modelo.setRowCount(0);

        VentaDAO ventaDAO = new VentaDAO();
        List<Object[]> ventas = ventaDAO.obtenerVentasConDetalles();

        for (Object[] fila : ventas)
        {
            modelo.addRow(fila);
        }
    }

    public void cargarDetallesPorVenta(int ventaId)
    {
        DetalleVentaDAO dao = new DetalleVentaDAO();
        List<Object[]> filas = dao.obtenerFilasParaTabla(ventaId);

        DefaultTableModel modelo = (DefaultTableModel) tablaDetalleVenta.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Object[] fila : filas)
        {
            modelo.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aaa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDetalleVenta;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables
}
