/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.ClienteDAO;
import dao.EmpleadoDAO;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.transform.stax.StAXResult;
import modelo.Cliente;
import modelo.Empleado;

/**
 *
 * @author chemo
 */
public class VtnEmpleado extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnEmpleado
     */
    public VtnEmpleado()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        buscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarEmpleados();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarEmpleados();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e)
            {
               filtrarEmpleados();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreJT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellidoJT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoJT = new javax.swing.JTextField();
        coreoJT = new javax.swing.JTextField();
        direccionJT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sueldoJT = new javax.swing.JTextField();
        rolCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usuarioJT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        activoCB = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        contraseñaTF = new javax.swing.JPasswordField();
        mostrarCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID ", "NOMBRE", "APELLIDO", "TELEFONO", "CORREO", "DIRECCION", "FECHA", "SALARIO", "ROL", "USUARIO", "CONTRASEÑA", "ACTIVO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));
        jPanel1.add(nombreJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 140, -1));

        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));
        jPanel1.add(apellidoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 150, -1));

        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, -1));
        jPanel1.add(telefonoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 300, -1));
        jPanel1.add(coreoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 310, -1));

        direccionJT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(direccionJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 310, -1));

        jLabel4.setText("Sueldo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, -1, -1));

        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 150, -1));

        jLabel6.setText("direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, -1, -1));

        jLabel7.setText("Fecha contracion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, -1, -1));

        sueldoJT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sueldoJTActionPerformed(evt);
            }
        });
        jPanel1.add(sueldoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 310, -1));

        rolCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero", "Empleado" }));
        rolCB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rolCBActionPerformed(evt);
            }
        });
        jPanel1.add(rolCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, -1, -1));

        jLabel8.setText("Rol:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        jLabel9.setText("usuario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));
        jPanel1.add(usuarioJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 310, -1));

        jLabel10.setText("Activo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, -1, -1));

        activoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(activoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 160, -1));

        jLabel11.setText("Contraseña:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, -1, -1));
        jPanel1.add(contraseñaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 310, -1));

        mostrarCheckBox.setText("Mostrar Contraseña");
        mostrarCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mostrarCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, -1, -1));

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 500, -1, -1));
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, -1));

        jButton4.setText("BAJA");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sueldoJTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sueldoJTActionPerformed
    {//GEN-HEADEREND:event_sueldoJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoJTActionPerformed

    private void mostrarCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mostrarCheckBoxActionPerformed
    {//GEN-HEADEREND:event_mostrarCheckBoxActionPerformed
        if (mostrarCheckBox.isSelected())
        {
            contraseñaTF.setEchoChar((char) 0);
        } else
        {
            contraseñaTF.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        String nombre = nombreJT.getText().trim();
        String apellido = apellidoJT.getText().trim();
        String telefono = telefonoJT.getText().trim();
        String email = coreoJT.getText().trim();
        String direccion = direccionJT.getText().trim();
        String password = contraseñaTF.getText().trim();
        String sueldo = sueldoJT.getText();
        int rol = rolCB.getSelectedIndex();
        String usuario = usuarioJT.getText();
        boolean activo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");

        if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || email.isEmpty() || direccion.isEmpty() || password.isEmpty() || usuario.isEmpty() || sueldo.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!telefono.matches("\\d{10}"))
        {
            JOptionPane.showMessageDialog(this, "Número de teléfono inválido. Debe contener exactamente 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$"))
        {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fecha.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date fechaSeleccionada = new java.sql.Date(fecha.getDate().getTime());

        double salario = Double.parseDouble(sueldo);
        Empleado nuevoEmpleado = new Empleado(nombre, apellido, telefono, email, direccion, fechaSeleccionada, salario, rol, usuario, password, activo);

        boolean registroExitoso = EmpleadoDAO.agregarEmpleado(nuevoEmpleado);

        if (registroExitoso)
        {
            JOptionPane.showMessageDialog(this, "Empleado registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(nombreJT, apellidoJT, telefonoJT, contraseñaTF, direccionJT, coreoJT, sueldoJT, usuarioJT);
            fecha.setDate(null);
            rolCB.setSelectedIndex(0);
            activoCB.setSelectedIndex(0);
            llenarTablaEmpleados();
        } else
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaEmpleados();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        int filaSeleccionada = tablaEmpleado.getSelectedRow();

        if (filaSeleccionada < 0 || filaSeleccionada >= tablaEmpleado.getRowCount())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar el epleado seleccionado?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaEmpleado.getModel();
            Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);

            int empleadoID;
            try
            {
                empleadoID = Integer.parseInt(valorCelda.toString());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error al obtener el ID del cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            EmpleadoDAO empleadoDAO = new EmpleadoDAO();
            boolean exito = empleadoDAO.eliminarEmpleado(empleadoID);

            if (exito)
            {
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTablaEmpleados();
                CtrlInterfaz.limpia(nombreJT, apellidoJT, telefonoJT, coreoJT, direccionJT, contraseñaTF, sueldoJT, usuarioJT);
                fecha.setDate(null);
                rolCB.setSelectedIndex(0);
                activoCB.setSelectedIndex(0);
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaEmpleadoMouseClicked
    {//GEN-HEADEREND:event_tablaEmpleadoMouseClicked
        int filaSeleccionada = tablaEmpleado.getSelectedRow();

        if (filaSeleccionada != -1)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaEmpleado.getModel();

            String nombre = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
            String apellido = (String) modeloTabla.getValueAt(filaSeleccionada, 2);
            String telefono = (String) modeloTabla.getValueAt(filaSeleccionada, 3);
            String email = (String) modeloTabla.getValueAt(filaSeleccionada, 4);
            String direccion = (String) modeloTabla.getValueAt(filaSeleccionada, 5);
            Date fecha = (Date) modeloTabla.getValueAt(filaSeleccionada, 6);
            Double salario = (Double) modeloTabla.getValueAt(filaSeleccionada, 7);
            String rol = modeloTabla.getValueAt(filaSeleccionada, 8).toString();
            String usuario = (String) modeloTabla.getValueAt(filaSeleccionada, 9);
            String contra = (String) modeloTabla.getValueAt(filaSeleccionada, 10);

            String estado = modeloTabla.getValueAt(filaSeleccionada, 11).toString();

            nombreJT.setText(nombre);
            apellidoJT.setText(apellido);
            telefonoJT.setText(telefono);
            coreoJT.setText(email);
            direccionJT.setText(direccion);
            this.fecha.setDate(fecha);
            contraseñaTF.setText(contra);
            usuarioJT.setText(usuario);
            String salarioSt = Double.toString(salario);
            sueldoJT.setText(salarioSt);

            if (estado.equals("Activo"))
            {
                activoCB.setSelectedItem("Activo");
            } else
            {
                activoCB.setSelectedItem("Inactivo");
            }

            switch (rol)
            {
                case "Administrador":
                    rolCB.setSelectedItem("Administrador");
                    break;
                case "Cajero":
                    rolCB.setSelectedItem("Cajero");
                    break;
                case "Empleado":
                    rolCB.setSelectedItem("Empleado");
                    break;
                default:
                    rolCB.setSelectedIndex(0);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tablaEmpleadoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        lipiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

        int filaSeleccionada = tablaEmpleado.getSelectedRow();

        if (filaSeleccionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) tablaEmpleado.getModel();

        String nuevoNombre = nombreJT.getText();
        String nuevoApellido = apellidoJT.getText();
        String nuevoTelefono = telefonoJT.getText();
        String nuevoCorreo = coreoJT.getText();
        String nuevaDireccion = direccionJT.getText();

        String nuevoSueldo = sueldoJT.getText();
        int nuevoRol = rolCB.getSelectedIndex();
        boolean nuevoActivo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");
        String nuevoUsuario = usuarioJT.getText();
        String nuevaContra = contraseñaTF.getText();

        if (nuevoNombre.isEmpty() || nuevoApellido.isEmpty() || nuevoTelefono.isEmpty() || nuevoCorreo.isEmpty() || nuevaDireccion.isEmpty() || nuevaContra.isEmpty() || nuevoUsuario.isEmpty() || nuevoSueldo.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nuevoTelefono.matches("\\d{10}"))
        {
            JOptionPane.showMessageDialog(this, "Número de teléfono inválido. Debe contener exactamente 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nuevoCorreo.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$"))
        {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fecha.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date nuevaFechaSeleccionada = new java.sql.Date(fecha.getDate().getTime());

        Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);
        int empleadoID;

        try
        {
            empleadoID = Integer.parseInt(valorCelda.toString());
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Empleado empleado = new Empleado();

        empleado.setNombre(nuevoNombre);
        empleado.setApellido(nuevoApellido);
        empleado.setTelefono(nuevoTelefono);
        empleado.setEmail(nuevoCorreo);
        empleado.setDireccion(nuevaDireccion);
        empleado.setFecha_contratación(nuevaFechaSeleccionada);
        empleado.setSalario(Double.parseDouble(nuevoSueldo));
        empleado.setRol_id(nuevoRol);
        empleado.setActivo(nuevoActivo);
        empleado.setUsuario(nuevoUsuario);
        empleado.setPassword(nuevaContra);
        empleado.setEmpleado_id(empleadoID);

        EmpleadoDAO empleadoDAO = new EmpleadoDAO();

        boolean exito = empleadoDAO.actualizarEmpleado(empleado);

        if (exito)
        {
            JOptionPane.showMessageDialog(this, "Empleado actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            llenarTablaEmpleados();
        } else
        {
            JOptionPane.showMessageDialog(this, "Error al actualizar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        lipiarCampos();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void rolCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rolCBActionPerformed
    {//GEN-HEADEREND:event_rolCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolCBActionPerformed

    public void lipiarCampos()
    {
        CtrlInterfaz.limpia(nombreJT, apellidoJT, telefonoJT, coreoJT, direccionJT, sueldoJT, usuarioJT, contraseñaTF);
        fecha.setDate(null);
        rolCB.setSelectedIndex(0);
        activoCB.setSelectedIndex(0);
    }

    private void llenarTablaEmpleados()
    {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaEmpleado.getModel();
        modeloTabla.setRowCount(0);

        List<Empleado> listarEmpleados = EmpleadoDAO.obtenerEmpleados();

        for (Empleado c : listarEmpleados)
        {
            String rolTexto;
            switch (c.getRol_id())
            {
                case 0:
                    rolTexto = "Administrador";
                    break;
                case 1:
                    rolTexto = "Cajero";
                    break;
                case 2:
                    rolTexto = "Empleado";
                    break;
                default:
                    rolTexto = "Desconocido";
                    break;
            }

            Object[] fila =
            {
                c.getEmpleado_id(),
                c.getNombre(),
                c.getApellido(),
                c.getTelefono(),
                c.getEmail(),
                c.getDireccion(),
                c.getFecha_contratación(),
                c.getSalario(),
                rolTexto,
                c.getUsuario(),
                c.getPassword(),
                c.isActivo() ? "Activo" : "Inactivo"
            };
            modeloTabla.addRow(fila);
        }
    }

    public void filtrarEmpleados()
    {
        String textoBusqueda = buscar.getText().trim().toLowerCase();
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaEmpleado.getModel();

        modeloTabla.setRowCount(0);

        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        List<Empleado> empleados = empleadoDAO.obtenerTodosLosEmpleados();

        for (Empleado empleado : empleados)
        {
            if (empleado.getNombre().toLowerCase().contains(textoBusqueda))
            {
                Object[] fila =
                {
                    empleado.getEmpleado_id(),
                    empleado.getNombre(),
                    empleado.getApellido(),
                    empleado.getTelefono(),
                    empleado.getEmail(),
                    empleado.getDireccion(),
                    empleado.getFecha_contratación(),
                    empleado.getSalario(),
                    obtenerNombreRol(empleado.getRol_id()), // Si quieres mostrar el nombre del rol
                    empleado.getUsuario(),
                    empleado.getPassword(),
                    empleado.isActivo() ? "Activo" : "Inactivo"
                };
                modeloTabla.addRow(fila);
            }
        }
    }

    public String obtenerNombreRol(int rolId)
    {
        switch (rolId)
        {
            case 1:
                return "Administrador";
            case 2:
                return "Cajero";
            case 3:
                return "Empleado";
            default:
                return "Desconocido";
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activoCB;
    private javax.swing.JTextField apellidoJT;
    private javax.swing.JTextField buscar;
    private javax.swing.JPasswordField contraseñaTF;
    private javax.swing.JTextField coreoJT;
    private javax.swing.JTextField direccionJT;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mostrarCheckBox;
    private javax.swing.JTextField nombreJT;
    private javax.swing.JComboBox<String> rolCB;
    private javax.swing.JTextField sueldoJT;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField telefonoJT;
    private javax.swing.JTextField usuarioJT;
    // End of variables declaration//GEN-END:variables
}
