/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.EmpleadoDAO;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author chemo
 */
public class VtnLogin extends javax.swing.JDialog
{

    private boolean acceso = false;
    private VtnPrincipal principal;

    /**
     * Creates new form VtnLoginAdministrador
     */
    public VtnLogin(java.awt.Frame parent, boolean modal, VtnPrincipal principal)
    {
        super(parent, modal);
        initComponents();
        this.principal = principal;
        setIconImage(getIconImage());

    }

     public Image getIconImage()
    {
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
        Image img = original.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contraseñaTF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        usuarioTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mostrarCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicia Sesion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        contraseñaTF.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(contraseñaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("CONTRASEÑA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        usuarioTF.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(usuarioTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        mostrarCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        mostrarCheckBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mostrarCheckBox.setText("Mostrar Contraseña");
        mostrarCheckBox.setToolTipText("");
        mostrarCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mostrarCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-sesion (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String usua = usuarioTF.getText().trim();
        String contra = new String(contraseñaTF.getPassword()).trim();

        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
        Empleado emp = empleadoDAO.obtenerRolEId(usua, contra);

        if (emp == null)
        {
            JOptionPane.showMessageDialog(this, "Credenciales inválidas o usuario inactivo.", "Error", JOptionPane.ERROR_MESSAGE);
            CtrlInterfaz.limpia(usuarioTF, contraseñaTF);
            acceso = false;
        } else
        {
            int idEmpleado = emp.getEmpleado_id();
            int rol = emp.getRol_id();
            acceso = true;

            principal.setDatosEmpleado(idEmpleado, rol, emp.getNombre());

            JOptionPane.showMessageDialog(this, "Acceso concedido.\nID: " + idEmpleado + " | Rol: " + rol, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mostrarCheckBoxActionPerformed
    {//GEN-HEADEREND:event_mostrarCheckBoxActionPerformed
        if (mostrarCheckBox.isSelected())
        {
            contraseñaTF.setEchoChar((char) 0);
        } else
        {
            contraseñaTF.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarCheckBoxActionPerformed

    public boolean isAcceso()
    {
        return acceso;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnPrincipal principal = new VtnPrincipal(); 
                VtnLogin dialog = new VtnLogin(principal, true, principal); 

                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });

                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mostrarCheckBox;
    private javax.swing.JTextField usuarioTF;
    // End of variables declaration//GEN-END:variables
}
