/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import javax.swing.JOptionPane;
import modelo.Provedor;
import dao.ProvedorDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chemo
 */
public class VtnProvedores extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnProvedores
     */
    public VtnProvedores()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        buscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProveedores();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProveedores();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProveedores();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreJT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contactoJT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoJT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailJT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        direccionJT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        activoCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvedor = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        buscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 580, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel8.setText("Proveedor");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 260, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 110, 80));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        nombreJT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(nombreJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Contacto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        contactoJT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(contactoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Teléfono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        telefonoJT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(telefonoJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 340, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Correo electrónico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        emailJT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(emailJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        direccionJT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel1.add(direccionJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Activo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        activoCB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        activoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jPanel1.add(activoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, -1));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, -1));

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setText("DATOS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 360, 440));

        tablaProvedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tablaProvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID PROVEDOR", "NOMBRE", "CONTACTO", "TELEFONO", "E-MAIL", "DIRECCION", "ACTIVO", "FECHA REGISTRO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaProvedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaProvedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProvedor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 790, 460));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura.png"))); // NOI18N
        jLabel7.setText("Bajas");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String nom = nombreJT.getText().trim();
        String contactoProv = contactoJT.getText().trim();
        String tel = telefonoJT.getText().trim();
        String correo = emailJT.getText().trim();
        String dir = direccionJT.getText().trim();
        boolean activo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");

        if (nom.isEmpty() || contactoProv.isEmpty() || tel.isEmpty() || correo.isEmpty() || dir.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!tel.matches("\\d{10}"))
        {
            JOptionPane.showMessageDialog(this, "Número de teléfono inválido. Debe contener exactamente 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$"))
        {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Provedor nuevoProveedor = new Provedor(nom, contactoProv, tel, correo, dir, activo);
        boolean registroExitoso = ProvedorDAO.agregarProveedor(nuevoProveedor);

        if (registroExitoso)
        {
            JOptionPane.showMessageDialog(this, "Proveedor registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(nombreJT, contactoJT, telefonoJT, emailJT, direccionJT);
            llenarTablaProveedores();
        } else
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarTablaProveedores();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tablaProvedorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaProvedorMouseClicked
    {//GEN-HEADEREND:event_tablaProvedorMouseClicked
        int filaSeleccionada = tablaProvedor.getSelectedRow();

        if (filaSeleccionada != -1)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaProvedor.getModel();

            String nombre = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
            String contacto = (String) modeloTabla.getValueAt(filaSeleccionada, 2);
            String telefono = (String) modeloTabla.getValueAt(filaSeleccionada, 3);
            String email = (String) modeloTabla.getValueAt(filaSeleccionada, 4);
            String direccion = (String) modeloTabla.getValueAt(filaSeleccionada, 5);
            String estado = (String) modeloTabla.getValueAt(filaSeleccionada, 6);

            nombreJT.setText(nombre);
            contactoJT.setText(contacto);
            telefonoJT.setText(telefono);
            emailJT.setText(email);
            direccionJT.setText(direccion);

            if (estado.equalsIgnoreCase("Activo"))
            {
                activoCB.setSelectedItem("ACTIVO");
            } else
            {
                activoCB.setSelectedItem("INACTIVO");
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tablaProvedorMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        CtrlInterfaz.limpia(nombreJT, contactoJT, telefonoJT, emailJT, direccionJT);
        activoCB.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel7MouseClicked
    {//GEN-HEADEREND:event_jLabel7MouseClicked
        int filaSeleccionada = tablaProvedor.getSelectedRow();

        if (filaSeleccionada < 0 || filaSeleccionada >= tablaProvedor.getRowCount())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un provedor valido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar el provedor seleccionado?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaProvedor.getModel();
            Object valorCelda = tablaProvedor.getValueAt(filaSeleccionada, 0);

            long provedorID;
            try
            {
                provedorID = Long.parseLong(valorCelda.toString());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error al obtener el código de la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ProvedorDAO provedorDAO = new ProvedorDAO();
            provedorDAO.eliminarProvedor(provedorID);

            llenarTablaProveedores();
            JOptionPane.showMessageDialog(this, "Categoría eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CtrlInterfaz.limpia(nombreJT, contactoJT, telefonoJT, emailJT, direccionJT);
            activoCB.setSelectedIndex(0);

        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        int filaSeleccionada = tablaProvedor.getSelectedRow();

        if (filaSeleccionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProvedor.getModel();

        String nuevoNombre = nombreJT.getText();
        String nuevoContacto = contactoJT.getText();
        String nuevoTelefono = telefonoJT.getText();
        String nuevoEmail = emailJT.getText();
        String nuevaDireccion = direccionJT.getText();
        String estadoSeleccionado = activoCB.getSelectedItem().toString();

        boolean activo = estadoSeleccionado.equalsIgnoreCase("Activo");

        Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);
        int proveedorId;

        try
        {
            proveedorId = Integer.parseInt(valorCelda.toString());
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Provedor proveedorActualizado = new Provedor();
        proveedorActualizado.setProvedor_id(proveedorId);
        proveedorActualizado.setNombre(nuevoNombre);
        proveedorActualizado.setContacto(nuevoContacto);
        proveedorActualizado.setTelefono(nuevoTelefono);
        proveedorActualizado.setEmail(nuevoEmail);
        proveedorActualizado.setDireccion(nuevaDireccion);
        proveedorActualizado.setActivo(activo);

        ProvedorDAO proveedorDAO = new ProvedorDAO();
        boolean exito = proveedorDAO.modificarProveedor(proveedorActualizado);

        if (exito)
        {
            JOptionPane.showMessageDialog(this, "Proveedor actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            llenarTablaProveedores();
        } else
        {
            JOptionPane.showMessageDialog(this, "Error al actualizar el proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void llenarTablaProveedores()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaProvedor.getModel();

        modelo.setRowCount(0);

        List<modelo.Provedor> proveedores = ProvedorDAO.listarProveedores();

        for (modelo.Provedor proveedor : proveedores)
        {
            modelo.addRow(new Object[]
            {
                proveedor.getProvedor_id(),
                proveedor.getNombre(),
                proveedor.getContacto(),
                proveedor.getTelefono(),
                proveedor.getEmail(),
                proveedor.getDireccion(),
                proveedor.isActivo() ? "Activo" : "Inactivo",
                proveedor.getFecha_registro()
            });
        }
    }

    public void filtrarProveedores()
    {
        String textoBusqueda = buscar.getText().trim().toLowerCase();
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProvedor.getModel();

        modeloTabla.setRowCount(0);

        ProvedorDAO proveedorDAO = new ProvedorDAO();
        List<Provedor> proveedores = proveedorDAO.obtenerTodosLosProveedores();

        for (Provedor proveedor : proveedores)
        {
            if (proveedor.getNombre().toLowerCase().contains(textoBusqueda))
            {
                Object[] fila =
                {
                    proveedor.getNombre(),
                    proveedor.getContacto(),
                    proveedor.getTelefono(),
                    proveedor.getEmail(),
                    proveedor.getDireccion(),
                    proveedor.isActivo() ? "Activo" : "Inactivo"
                };
                modeloTabla.addRow(fila);
            }
        }
    }
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activoCB;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField contactoJT;
    private javax.swing.JTextField direccionJT;
    private javax.swing.JTextField emailJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreJT;
    private javax.swing.JTable tablaProvedor;
    private javax.swing.JTextField telefonoJT;
    // End of variables declaration//GEN-END:variables
}
