/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dao.DetalleVentaDAO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author chemo
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    private int idEmpleado;
    private int rolEmnpleado;
    private String nombreEmpleado;

    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal()
    {
        initComponents();
        menuAdmin.setEnabled(false);
        menuCaja.setEnabled(false);
        opcCerrarSecion.setEnabled(false);
        menuDetalleVenta.setEnabled(false);
        setIconImage(getIconImage());
    }
    
    public Image getIconImage()
    {
        ImageIcon original = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
        Image img = original.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelControl = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuDetalleVenta = new javax.swing.JMenu();
        menuCaja = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        opcCerrarSecion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supermercado");
        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(171, 30));

        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador.png"))); // NOI18N
        menuAdmin.setText("Administrador");
        menuAdmin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/opciones.png"))); // NOI18N
        jMenu3.setText("Categorias");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu3MouseClicked(evt);
            }
        });
        menuAdmin.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        jMenu4.setText("Clientes");
        jMenu4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu4MouseClicked(evt);
            }
        });
        menuAdmin.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado-de-oficina.png"))); // NOI18N
        jMenu5.setText("Empleados");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu5MouseClicked(evt);
            }
        });
        menuAdmin.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpieza.png"))); // NOI18N
        jMenu7.setText("Productos");
        jMenu7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu7MouseClicked(evt);
            }
        });
        menuAdmin.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion.png"))); // NOI18N
        jMenu6.setText("Provedores");
        jMenu6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu6MouseClicked(evt);
            }
        });
        menuAdmin.add(jMenu6);

        jMenuBar1.add(menuAdmin);

        menuDetalleVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vendedor.png"))); // NOI18N
        menuDetalleVenta.setText("Detalles Ventas");
        menuDetalleVenta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuDetalleVenta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuDetalleVentaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDetalleVenta);

        menuCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajero.png"))); // NOI18N
        menuCaja.setText("Caja");
        menuCaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuCaja.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuCajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCaja);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-sesion.png"))); // NOI18N
        jMenu9.setText("Sesión");
        jMenu9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datos-del-usuario.png"))); // NOI18N
        jMenu10.setText("Iniciar Sesion");
        jMenu10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu9.add(jMenu10);

        opcCerrarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-con-llave.png"))); // NOI18N
        opcCerrarSecion.setText("Cerrar Sesion");
        opcCerrarSecion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        opcCerrarSecion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                opcCerrarSecionMouseClicked(evt);
            }
        });
        jMenu9.add(opcCerrarSecion);

        jMenuBar1.add(jMenu9);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado.png"))); // NOI18N
        jMenu2.setText("Empleado");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu3MouseClicked
    {//GEN-HEADEREND:event_jMenu3MouseClicked
        panelControl.removeAll();
        VtnCategorias categorias = new VtnCategorias();
        panelControl.add(categorias).setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu4MouseClicked
    {//GEN-HEADEREND:event_jMenu4MouseClicked
        panelControl.removeAll();
        VtnClientes clientes = new VtnClientes();
        panelControl.add(clientes).setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu6MouseClicked
    {//GEN-HEADEREND:event_jMenu6MouseClicked
        panelControl.removeAll();
        VtnProvedores provedores = new VtnProvedores();
        panelControl.add(provedores).setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu7MouseClicked
    {//GEN-HEADEREND:event_jMenu7MouseClicked
        panelControl.removeAll();
        VtnProductos productos = new VtnProductos();
        panelControl.add(productos).setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu5MouseClicked
    {//GEN-HEADEREND:event_jMenu5MouseClicked
        panelControl.removeAll();
        VtnEmpleado empleado = new VtnEmpleado();
        panelControl.add(empleado).setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void menuCajaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuCajaMouseClicked
    {//GEN-HEADEREND:event_menuCajaMouseClicked
        boolean activo = menuCaja.isEnabled();

        if (activo)
        {
            panelControl.removeAll();
            VtnVenta venta = new VtnVenta(idEmpleado);
            panelControl.add(venta).setVisible(true);
        } else
        {
            JOptionPane.showMessageDialog(this, "Inicie sesion.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuCajaMouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu10MouseClicked
    {//GEN-HEADEREND:event_jMenu10MouseClicked
        VtnLogin login = new VtnLogin(this, true, this);
        login.setVisible(true);

        if (login.isAcceso())
        {
            switch (rolEmnpleado)
            {
                case 0:
                    JOptionPane.showMessageDialog(this, "Bienvenido administrador");
                    menuAdmin.setEnabled(true);
                    menuCaja.setEnabled(true);
                    opcCerrarSecion.setEnabled(true);
                    menuDetalleVenta.setEnabled(true);
                    break;

                case 1:
                    JOptionPane.showMessageDialog(this, "Bienvenido cajero");
                    menuCaja.setEnabled(true);
                    opcCerrarSecion.setEnabled(true);
                    break;

                case 2:
                    JOptionPane.showMessageDialog(this, "Bienvenido área de almacén");
                    break;

                default:
                    JOptionPane.showMessageDialog(this, "Rol desconocido o no autorizado", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
    }//GEN-LAST:event_jMenu10MouseClicked

    private void opcCerrarSecionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_opcCerrarSecionMouseClicked
    {//GEN-HEADEREND:event_opcCerrarSecionMouseClicked
        boolean acceso = opcCerrarSecion.isEnabled();

        if (acceso)
        {
            cerrarSesion();
        } else
        {
            JOptionPane.showMessageDialog(this, "Inicie Sesion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_opcCerrarSecionMouseClicked

    private void menuDetalleVentaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuDetalleVentaMouseClicked
    {//GEN-HEADEREND:event_menuDetalleVentaMouseClicked
        boolean acceso = menuDetalleVenta.isEnabled();
        if (acceso)
        {
            panelControl.removeAll();
            VtnDetalleVenta detalleVenta = new VtnDetalleVenta();
            panelControl.add(detalleVenta).setVisible(true);
        } else
        {
            JOptionPane.showMessageDialog(this, "Inicie sesion como administrador", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuDetalleVentaMouseClicked

    public void setDatosEmpleado(int idEmpleado, int rol, String nombre)
    {
        this.idEmpleado = idEmpleado;
        this.rolEmnpleado = rol;
        this.nombreEmpleado = nombre;

        jMenu2.setText(nombreEmpleado);

        System.out.println("Empleado logueado: ID=" + idEmpleado + " Rol=" + rol);
    }

    public void cerrarSesion()
    {

        idEmpleado = -1;
        rolEmnpleado = -1;
        nombreEmpleado = "";

        jMenu2.setText("Usuario");
        menuAdmin.setEnabled(false);
        menuCaja.setEnabled(false);
        menuDetalleVenta.setEnabled(false);
        opcCerrarSecion.setEnabled(false);

        panelControl.removeAll();
        panelControl.repaint();
        panelControl.revalidate();

        JOptionPane.showMessageDialog(this, "Sesión cerrada.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenu menuCaja;
    private javax.swing.JMenu menuDetalleVenta;
    private javax.swing.JMenu opcCerrarSecion;
    private javax.swing.JDesktopPane panelControl;
    // End of variables declaration//GEN-END:variables
}
