/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.CategoriaDAO;
import dao.InventarioDAO;
import dao.ProductoDAO;
import dao.ProvedorDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Inventario;
import modelo.Producto;
import modelo.Provedor;

/**
 *
 * @author chemo
 */
public class VtnProductos extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnProductos
     */
    public VtnProductos()
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        buscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener()
        {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProductos();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProductos();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e)
            {
                filtrarProductos();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreJT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descripcionJT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precioCompraJT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        precioVentaJT = new javax.swing.JTextField();
        stockMinS = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoriaCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        activoCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        provedorCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        stockInicialS = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(1200, 560));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID PRODUCTO", "NOMBRE", "DESCRIPCCION", "PRECIO COMPRA", "PRECIO VENTA", "STOCK MIN", "CATEGORIA", "PROVEEDOR", "ACTIVO", "FECHA CREACION", "INVENTARIO"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1200, 350));

        jLabel1.setText("buscar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(nombreJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        jLabel2.setText("Descripcion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(descripcionJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, -1));

        jLabel3.setText("Precio compra");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(precioCompraJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        jLabel4.setText("Stock Inicial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));
        jPanel1.add(precioVentaJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 240, -1));

        stockMinS.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        stockMinS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(stockMinS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 100, -1));

        jLabel5.setText("Precio venta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel6.setText("Categoria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        categoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(categoriaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 240, -1));

        jLabel7.setText("Activo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        activoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(activoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 100, -1));

        jLabel8.setText("Provedor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        provedorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(provedorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, -1));

        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jButton2.setText("modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jButton3.setText("limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 650, -1));

        jLabel9.setText("Nombre");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton4.setText("eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, -1, -1));

        stockInicialS.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(stockInicialS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 90, -1));

        jLabel10.setText("Stock Minimo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarComboCategoria(categoriaCB);
        llenarComboProvedor(provedorCB);
        llenarTablaProductos();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String nombre = nombreJT.getText().trim();
        String descripcion = descripcionJT.getText().trim();
        String precioCompraStr = precioCompraJT.getText().trim();
        String precioVentaStr = precioVentaJT.getText().trim();
        int stockMinimo = (Integer) stockMinS.getValue();
        int stockInicial = (Integer) stockInicialS.getValue();
        String categoriaSeleccionada = (String) categoriaCB.getSelectedItem();
        String proveedorSeleccionado = (String) provedorCB.getSelectedItem();
        boolean activo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");

        if (nombre.isEmpty() || precioCompraStr.isEmpty() || precioVentaStr.isEmpty()
                || categoriaSeleccionada == null || proveedorSeleccionado == null)
        {
            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double precioCompra;
        double precioVenta;
        try
        {
            precioCompra = Double.parseDouble(precioCompraStr);
            precioVenta = Double.parseDouble(precioVentaStr);
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Precios inválidos. Use solo números con punto decimal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CategoriaDAO categoriaDAO = new CategoriaDAO();
        ProvedorDAO provedorDAO = new ProvedorDAO();

        int categoriaId = categoriaDAO.obtenerIdPorNombre(categoriaSeleccionada);
        int proveedorId = provedorDAO.obtenerIdPorNombre(proveedorSeleccionado);

        if (categoriaId == -1 || proveedorId == -1)
        {
            JOptionPane.showMessageDialog(this, "Error al obtener ID de categoría o proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Producto nuevoProducto = new Producto();
        nuevoProducto.setNombre(nombre);
        nuevoProducto.setDescripcion(descripcion);
        nuevoProducto.setPrecio_compra(precioCompra);
        nuevoProducto.setPrecio_venta(precioVenta);
        nuevoProducto.setStock_minimo(stockMinimo);
        nuevoProducto.setCategoria_id(categoriaId);
        nuevoProducto.setProveedor_id(proveedorId);
        nuevoProducto.setActivo(activo);

        ProductoDAO productoDAO = new ProductoDAO();
        int productoId = productoDAO.agregarProductoYObtenerId(nuevoProducto);

        if (productoId > 0)
        {
            InventarioDAO inventarioDAO = new InventarioDAO();
            Inventario inventario = new Inventario(productoId, stockInicial);
            boolean inventarioAgregado = inventarioDAO.insertarInventario(inventario);

            if (inventarioAgregado)
            {
                JOptionPane.showMessageDialog(this, "Producto e inventario registrados exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                CtrlInterfaz.limpia(nombreJT, descripcionJT, precioCompraJT, precioVentaJT);
                stockMinS.setValue(1);
                stockInicialS.setValue(0);
                categoriaCB.setSelectedIndex(0);
                provedorCB.setSelectedIndex(0);
                activoCB.setSelectedItem("Activo");
                llenarTablaProductos();
            } else
            {
                JOptionPane.showMessageDialog(this, "Producto registrado pero falló el inventario.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();

        String nombre = nombreJT.getText().trim();
        String descripcion = descripcionJT.getText().trim();
        String precioCompraStr = precioCompraJT.getText().trim();
        String precioVentaStr = precioVentaJT.getText().trim();
        int stockMinimo = (int) stockMinS.getValue();
        int nuevaCantidadInventario = (int) stockInicialS.getValue();
        String categoriaSeleccionada = (String) categoriaCB.getSelectedItem();
        String proveedorSeleccionado = (String) provedorCB.getSelectedItem();
        boolean activo = activoCB.getSelectedItem().toString().equalsIgnoreCase("Activo");

        if (nombre.isEmpty() || descripcion.isEmpty() || precioCompraStr.isEmpty() || precioVentaStr.isEmpty()
                || categoriaSeleccionada == null || proveedorSeleccionado == null)
        {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try
        {
            double precioCompra = Double.parseDouble(precioCompraStr);
            double precioVenta = Double.parseDouble(precioVentaStr);

            CategoriaDAO categoriaDAO = new CategoriaDAO();
            ProvedorDAO provedorDAO = new ProvedorDAO();

            int idCategoria = categoriaDAO.obtenerIdPorNombre(categoriaSeleccionada);
            int idProveedor = provedorDAO.obtenerIdPorNombre(proveedorSeleccionado);

            Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);
            int productoId = Integer.parseInt(valorCelda.toString());

            Producto producto = new Producto(nombre, descripcion, precioCompra, precioVenta, stockMinimo, idCategoria, idProveedor, activo);
            producto.setProducto_id(productoId);

            ProductoDAO productoDAO = new ProductoDAO();
            boolean exito = productoDAO.actualizarProducto(producto);

            InventarioDAO inventarioDAO = new InventarioDAO();
            boolean inventarioActualizado = inventarioDAO.actualizarCantidadInventario(productoId, nuevaCantidadInventario);

            if (exito)
            {
                if (!inventarioActualizado)
                {
                    JOptionPane.showMessageDialog(this, "Producto actualizado, pero ocurrió un error al actualizar el inventario.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else
                {
                    JOptionPane.showMessageDialog(this, "Producto e inventario actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }
                llenarTablaProductos();
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al actualizar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Error al convertir precios o stock. Verifique los valores ingresados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaProductosMouseClicked
    {//GEN-HEADEREND:event_tablaProductosMouseClicked
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada != -1)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();

            String nombre = modeloTabla.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = modeloTabla.getValueAt(filaSeleccionada, 2).toString();
            String precioCompra = modeloTabla.getValueAt(filaSeleccionada, 3).toString();
            String precioVenta = modeloTabla.getValueAt(filaSeleccionada, 4).toString();
            String stockMinimo = modeloTabla.getValueAt(filaSeleccionada, 5).toString();
            String categoria = modeloTabla.getValueAt(filaSeleccionada, 6).toString();
            String proveedor = modeloTabla.getValueAt(filaSeleccionada, 7).toString();
            String estado = modeloTabla.getValueAt(filaSeleccionada, 8).toString();

            int productoId = Integer.parseInt(modeloTabla.getValueAt(filaSeleccionada, 0).toString());

            nombreJT.setText(nombre);
            descripcionJT.setText(descripcion);
            precioCompraJT.setText(precioCompra);
            precioVentaJT.setText(precioVenta);
            stockMinS.setValue(Integer.parseInt(stockMinimo));
            categoriaCB.setSelectedItem(categoria);
            provedorCB.setSelectedItem(proveedor);

            InventarioDAO inventarioDAO = new InventarioDAO();
            int cantidadInventario = inventarioDAO.obtenerCantidadPorProductoId(productoId);
            stockInicialS.setValue(cantidadInventario);

            if (estado.equalsIgnoreCase("Activo"))
            {
                activoCB.setSelectedItem("Activo");
            } else
            {
                activoCB.setSelectedItem("Inactivo");
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        CtrlInterfaz.limpia(nombreJT, descripcionJT, precioCompraJT, precioVentaJT);
        stockMinS.setValue(1);
        provedorCB.setSelectedIndex(0);
        categoriaCB.setSelectedIndex(0);
        activoCB.setSelectedIndex(0);
        stockInicialS.setValue(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada < 0 || filaSeleccionada >= tablaProductos.getRowCount())
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar el producto seleccionado?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION)
        {
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();
            Object valorCelda = modeloTabla.getValueAt(filaSeleccionada, 0);

            int productoID;
            try
            {
                productoID = Integer.parseInt(valorCelda.toString());
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error al obtener el ID del producto.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ProductoDAO productoDAO = new ProductoDAO();
            boolean exito = productoDAO.eliminarProducto(productoID);

            if (exito)
            {
                JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTablaProductos();
                llenarTablaProductos();
            } else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void llenarTablaProductos()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        ProductoDAO productoDAO = new ProductoDAO();
        List<Object[]> productos = productoDAO.listarProductosConNombres();

        for (Object[] fila : productos)
        {
            modelo.addRow(fila);
        }
    }

    public void filtrarProductos()
    {
        String textoBusqueda = buscar.getText().trim().toLowerCase();
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();

        modeloTabla.setRowCount(0); 

        ProductoDAO productoDAO = new ProductoDAO();
        List<Object[]> productos = productoDAO.listarProductosConNombresYStock(); 

        for (Object[] fila : productos)
        {
            String nombreProducto = fila[1].toString().toLowerCase();
            if (nombreProducto.contains(textoBusqueda))
            {
                modeloTabla.addRow(fila);
            }
        }
    }

    public void llenarComboCategoria(JComboBox<String> comboCategoria)
    {
        CategoriaDAO categoriaDAO = new CategoriaDAO();

        List<Categoria> listaCategoria = categoriaDAO.obtenerTodosLasCategorias();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Seleccione una Categoria");

        for (Categoria categoria : listaCategoria)
        {
            modelo.addElement(categoria.getNombre());
        }
        comboCategoria.setModel(modelo);
    }

    public void llenarComboProvedor(JComboBox<String> comboProvedor)
    {
        ProvedorDAO provedorDAO = new ProvedorDAO();

        List<Provedor> listaProvedor = provedorDAO.obtenerTodosLosProveedores();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Seleccione una Provedor");

        for (Provedor provedor : listaProvedor)
        {
            modelo.addElement(provedor.getNombre());
        }
        comboProvedor.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activoCB;
    private javax.swing.JTextField buscar;
    private javax.swing.JComboBox<String> categoriaCB;
    private javax.swing.JTextField descripcionJT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreJT;
    private javax.swing.JTextField precioCompraJT;
    private javax.swing.JTextField precioVentaJT;
    private javax.swing.JComboBox<String> provedorCB;
    private javax.swing.JSpinner stockInicialS;
    private javax.swing.JSpinner stockMinS;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
