/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import cjb.ci.CtrlInterfaz;
import dao.CategoriaDAO;
import dao.ClienteDAO;
import dao.DetalleVentaDAO;
import dao.ProductoDAO;
import dao.VentaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Cliente;
import modelo.DetallesVenta;
import modelo.Inventario;
import modelo.Venta;

/**
 *
 * @author chemo
 */
public class VtnVenta extends javax.swing.JInternalFrame
{

    private int idEmpleado;

    /**
     * Creates new form VtnVenta
     */
    public VtnVenta(int idEmpleado)
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.idEmpleado = idEmpleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        categoriaCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cantidadJS = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        campoTotalVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoIVA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDescuento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoSubtotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clienteCB = new javax.swing.JComboBox<>();
        pagoCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaCB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                categoriaCBActionPerformed(evt);
            }
        });
        jPanel1.add(categoriaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        jLabel1.setText("Categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID PRODUCTO", "NOMBRE", "PRECIO", "STOCK"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, 420));

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID PRODUCTO", "PRODUCTO", "CANTIDAD", "PREC. UNITARIO", "TOTAL"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCarrito);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 680, 340));

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton2.setText("ELIMINAR");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jButton3.setText("MODIFICIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        cantidadJS.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(cantidadJS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 90, -1));

        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        jPanel1.add(campoTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 140, -1));

        jLabel3.setText("Total Venta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, -1, -1));
        jPanel1.add(campoIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 460, 140, -1));

        jLabel4.setText("IVA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, -1, -1));
        jPanel1.add(campoDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 410, 140, -1));

        jLabel5.setText("Descuento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, -1, -1));
        jPanel1.add(campoSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 360, 140, -1));

        jLabel6.setText("Subtotal:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, -1, -1));

        jButton4.setText("PAGAR");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, -1, -1));

        jButton5.setText("CANCELAR");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        jLabel7.setText("Cliente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        clienteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(clienteCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 130, -1));

        pagoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        jPanel1.add(pagoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 130, -1));

        jLabel8.setText("Metodo de pago:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameOpened
    {//GEN-HEADEREND:event_formInternalFrameOpened
        llenarComboCategoria(categoriaCB);
        llenarComboCliente(clienteCB);
    }//GEN-LAST:event_formInternalFrameOpened

    private void categoriaCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_categoriaCBActionPerformed
    {//GEN-HEADEREND:event_categoriaCBActionPerformed
        String categoriaSeleccionada = categoriaCB.getSelectedItem().toString();

        if (!categoriaSeleccionada.equals("Seleccione una Categoría"))
        {
            llenarTablaProductosPorCategoria(categoriaSeleccionada);
        }
    }//GEN-LAST:event_categoriaCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1)
        {
            JOptionPane.showMessageDialog(this, "Seleccione un producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaProductos.getValueAt(fila, 0);
        String nombre = tablaProductos.getValueAt(fila, 1).toString();
        double precio = Double.parseDouble(tablaProductos.getValueAt(fila, 2).toString());
        int stock = Integer.parseInt(tablaProductos.getValueAt(fila, 3).toString());
        int cantidad = (int) cantidadJS.getValue();

        if (cantidad <= 0)
        {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cantidad > stock)
        {
            JOptionPane.showMessageDialog(this, "La cantidad excede el stock disponible.", "Stock insuficiente", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double total = cantidad * precio;

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        modelo.addRow(new Object[]
        {
            id,
            nombre,
            cantidad,
            precio,
            total
        });

        int nuevoStock = stock - cantidad;
        tablaProductos.setValueAt(nuevoStock, fila, 3);

        actualizarResumenVenta();
        cantidadJS.setValue(1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        int fila = tablaCarrito.getSelectedRow();

        if (fila >= 0)
        {
            DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
            modelo.removeRow(fila);
            actualizarResumenVenta();
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto del carrito para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        int fila = tablaCarrito.getSelectedRow();

        if (fila >= 0)
        {
            int nuevaCantidad = (int) cantidadJS.getValue();

            if (nuevaCantidad <= 0)
            {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();

            double precioUnitario = Double.parseDouble(modelo.getValueAt(fila, 4).toString());
            double nuevoTotal = precioUnitario * nuevaCantidad;

            modelo.setValueAt(nuevaCantidad, fila, 2);
            modelo.setValueAt(nuevoTotal, fila, 4);

            actualizarResumenVenta();
        } else
        {
            JOptionPane.showMessageDialog(this, "Seleccione un producto del carrito para modificar la cantidad.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        String nombreCliente = (String) clienteCB.getSelectedItem();

        if (nombreCliente == null || nombreCliente.equals("Seleccione un Cliente"))
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ClienteDAO clienteDAO = new ClienteDAO();
        int clienteID = clienteDAO.obtenerIdPorNombreCompleto(nombreCliente);

        if (clienteID == -1)
        {
            JOptionPane.showMessageDialog(this, "Cliente no válido o no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int metodoPago = pagoCB.getSelectedIndex();
        double total = Double.parseDouble(campoTotalVenta.getText());
        double descuento = Double.parseDouble(campoDescuento.getText());
        double iva = Double.parseDouble(campoIVA.getText());

        Venta nuevaVenta = new Venta(total, descuento, iva, clienteID, idEmpleado, metodoPago, 1);

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        List<DetallesVenta> listaDetalles = new ArrayList<>();

        for (int i = 0; i < modelo.getRowCount(); i++)
        {
            int idProducto = (int) modelo.getValueAt(i, 0);
            int cantidad = (int) modelo.getValueAt(i, 2);
            double precioU = (double) modelo.getValueAt(i, 3);
            double subtotal = (double) modelo.getValueAt(i, 4);

            DetallesVenta detalle = new DetallesVenta(0, idProducto, cantidad, precioU, subtotal);
            listaDetalles.add(detalle);
        }

        VentaDAO dao = new VentaDAO();
        boolean exito = dao.registrarVentaConDetalles(nuevaVenta, listaDetalles);

        if (exito)
        {
            JOptionPane.showMessageDialog(this, "¡Venta registrada correctamente!");
            limpiaCampos();
        } else
        {
            JOptionPane.showMessageDialog(this, "Error al registrar la venta. No se guardó nada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void llenarComboCategoria(JComboBox<String> comboCategoria)
    {
        CategoriaDAO categoriaDAO = new CategoriaDAO();

        List<Categoria> listaCategoria = categoriaDAO.obtenerTodosLasCategorias();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Seleccione una Categoria");

        for (Categoria categoria : listaCategoria)
        {
            modelo.addElement(categoria.getNombre());
        }
        comboCategoria.setModel(modelo);
    }

    public void llenarComboCliente(JComboBox<String> comboCliente)
    {
        ClienteDAO clienteDAO = new ClienteDAO();

        List<Cliente> listaClientes = clienteDAO.obtenerTodosLosClientes();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Seleccione un Cliente");

        for (Cliente cliente : listaClientes)
        {
            String nombreCompleto = cliente.getNombre() + " " + cliente.getApellido();
            modelo.addElement(nombreCompleto);
        }

        comboCliente.setModel(modelo);
    }

    public void llenarTablaProductosPorCategoria(String nombreCategoria)
    {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();
        modeloTabla.setRowCount(0);

        ProductoDAO productoDAO = new ProductoDAO();
        List<Inventario> lista = productoDAO.obtenerProductosPorCategoria(nombreCategoria);

        for (Inventario inv : lista)
        {
            Object[] fila =
            {
                inv.getProducto_id(),
                inv.getNombre(),
                inv.getPrecio_venta(),
                inv.getCantidad()
            };
            modeloTabla.addRow(fila);
        }
    }

    private void actualizarResumenVenta()
    {
        double subtotal = 0;

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        int filas = modelo.getRowCount();

        for (int i = 0; i < filas; i++)
        {
            double totalFila = Double.parseDouble(modelo.getValueAt(i, 4).toString());
            subtotal += totalFila;
        }

        double descuento = 0;
        if (subtotal > 1500)
        {
            descuento = subtotal * 0.05;
        } else if (subtotal > 1000)
        {
            descuento = subtotal * 0.03;
        }

        double iva = subtotal * 0.16;
        double total = subtotal + iva - descuento;

        campoSubtotal.setText(String.format("%.2f", subtotal));
        campoDescuento.setText(String.format("%.2f", descuento));
        campoIVA.setText(String.format("%.2f", iva));
        campoTotalVenta.setText(String.format("%.2f", total));
    }

    private void limpiaCampos()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        modelo.setRowCount(0);

        DefaultTableModel modelo1 = (DefaultTableModel) tablaProductos.getModel();
        modelo1.setRowCount(0);

        CtrlInterfaz.limpia(campoSubtotal, campoDescuento, campoIVA, campoTotalVenta);

        cantidadJS.setValue(1);

        tablaProductos.clearSelection();
        categoriaCB.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoDescuento;
    private javax.swing.JTextField campoIVA;
    private javax.swing.JTextField campoSubtotal;
    private javax.swing.JTextField campoTotalVenta;
    private javax.swing.JSpinner cantidadJS;
    private javax.swing.JComboBox<String> categoriaCB;
    private javax.swing.JComboBox<String> clienteCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> pagoCB;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
